travis:
  secure:
    BINSTAR_TOKEN: tUcKFesNN7WNkNkjZ4CRqD8aatRQg5IzTKJ0jk0BW5ejJ/KgsdUs/FcmznjnIG8yYjI4OLWEtYApOqi0m4vFN7X0WymloammPa/PxxKldSTdXCtHdE5Wp+kxtWUVzBw/b88XpBaz0ZTmf+Okn6xStSZoqcIm+D5DS5yxbudNhjOQhgRDqXaFZi4Dd4CjgE/YHj4jBiIhmoOAAweiW1o8kKYU+oy23jM6tIOSpJb3+gv98735ODlU0fZUAUQEN3E1IB0ICaR6RzOvbKpsho50HCuMnu8/jBZtqeFMqn3UXMGoGY69rYt7VvqllE0IRJsEhAbqut8xrsBwBSErqdlzWPq0mofdVWd6i0RGSj/s0vJXVfu/qjKI8LYruRtvge1oyVFe+DTYUOK11JIXjpeHvygduNMgqWPT3O8T75RTMqKvuS77jqqPfIiJMubnmrERYK21flJPNLvVBQOGXL+feBSiZ8JFv8vLifHSuEU2zXPDCDKx6VBzxzobMyQB8Jo1HFp4ELUvXuxajW8wsFZhdwhltmEO3VCfjWIzN+ffqFcWJtusRHSmH+2HV2zzvMN80kjq0/ZlWqk7RwcZX+olSDszk3/Ta0czrIourrHSea9k8ApL7i3lA+/7KPw7zibC0mVaYPxJwqZsUXmsz80mKcCpJOaY6spoqMDItlrgevU=
conda_forge_output_validation: true
bot:
  check_solvable: True
  
